"""
Diversified NSE (.NS) universe for multi-layer scanning.

Segments (indicative, not an official index rebalance):
- Large cap: highly liquid large names (~80–100)
- Mid cap: broader liquid mid-tier (~120–150)
- Small cap: smaller but still liquid names (~80–100)

Total target ~250–300 symbols. Yahoo Finance coverage varies; the downloader skips failures.
Constituents drift over time — treat as a **research/demo** universe.
"""

from __future__ import annotations

from utils import NIFTY50_TICKERS, parse_tickers_text

# Large cap: NIFTY 50 plus additional mega/large liquid names (NEXT 50–style overlap possible).
_LARGE_CAP_EXTRA: list[str] = [
    "ADANIGREEN.NS",
    "APOLLOHOSP.NS",
    "AUROPHARMA.NS",
    "BANDHANBNK.NS",
    "BERGEPAINT.NS",
    "BIOCON.NS",
    "BOSCHLTD.NS",
    "CHOLAFIN.NS",
    "COLPAL.NS",
    "DABUR.NS",
    "DLF.NS",
    "GAIL.NS",
    "GLENMARK.NS",
    "GODREJCP.NS",
    "HAVELLS.NS",
    "HDFCAMC.NS",
    "ICICIGI.NS",
    "ICICIPRULI.NS",
    "IRCTC.NS",
    "LICI.NS",
    "LUPIN.NS",
    "MARICO.NS",
    "MOTHERSON.NS",
    "MUTHOOTFIN.NS",
    "NAUKRI.NS",
    "NMDC.NS",
    "OFSS.NS",
    "PAGEIND.NS",
    "PEL.NS",
    "PETRONET.NS",
    "PIIND.NS",
    "PNB.NS",
    "POLYCAB.NS",
    "SRF.NS",
    "TORNTPHARM.NS",
    "TVSMOTOR.NS",
    "UNITDSPR.NS",
    "VBL.NS",
    "ZYDUSLIFE.NS",
    "ABB.NS",
    "ACC.NS",
    "ALKEM.NS",
    "AMBUJACEM.NS",
    "CANBK.NS",
    "CHAMBLFERT.NS",
    "CONCOR.NS",
    "CUMMINSIND.NS",
    "DIXON.NS",
    "ESCORTS.NS",
    "FEDERALBNK.NS",
    "GMRINFRA.NS",
    "GUJGASLTD.NS",
    "HAL.NS",
    "HINDPETRO.NS",
    "IDFCFIRSTB.NS",
    "IGL.NS",
    "INDHOTEL.NS",
    "INDUSTOWER.NS",
    "IPCALAB.NS",
    "JINDALSTEL.NS",
    "JKCEMENT.NS",
    "JUBLFOOD.NS",
    "LALPATHLAB.NS",
    "LAURUSLABS.NS",
    "LINDEINDIA.NS",
    "LTIM.NS",
    "MANKIND.NS",
    "MAXHEALTH.NS",
    "MPHASIS.NS",
    "MRF.NS",
    "PERSISTENT.NS",
    "PHOENIXLTD.NS",
    "PIDILITIND.NS",
    "PFC.NS",
    "RECLTD.NS",
    "SIEMENS.NS",
    "SRTRANSFIN.NS",
    "TATACOMM.NS",
    "TIINDIA.NS",
    "TRENT.NS",
    "UBL.NS",
    "VOLTAS.NS",
    "WHIRLPOOL.NS",
    "YESBANK.NS",
    "ZOMATO.NS",
]

# Mid cap: broader set (liquidity varies; Layer 1 will filter).
_MID_CAP: list[str] = [
    "AARTIIND.NS",
    "ABCAPITAL.NS",
    "ABFRL.NS",
    "AJANTPHARM.NS",
    "APARINDS.NS",
    "ASHOKLEY.NS",
    "ASTERDM.NS",
    "ATUL.NS",
    "AUBANK.NS",
    "BAJAJHLDNG.NS",
    "BALKRISIND.NS",
    "BATAINDIA.NS",
    "BHARATFORG.NS",
    "BHEL.NS",
    "BLUEDART.NS",
    "BRIGADE.NS",
    "CANFINHOME.NS",
    "CASTROLIND.NS",
    "CENTRALBK.NS",
    "CESC.NS",
    "CHOLAHLDNG.NS",
    "COCHINSHIP.NS",
    "COFORGE.NS",
    "COROMANDEL.NS",
    "CREDITACC.NS",
    "CRISIL.NS",
    "CROMPTON.NS",
    "CSBBANK.NS",
    "DEEPAKNTR.NS",
    "DELHIVERY.NS",
    "DEVYANI.NS",
    "EIHOTEL.NS",
    "ENDURANCE.NS",
    "ENGINERSIN.NS",
    "EXIDEIND.NS",
    "FORTIS.NS",
    "GLAXO.NS",
    "GNFC.NS",
    "GODREJIND.NS",
    "GODREJPROP.NS",
    "GRANULES.NS",
    "GRAPHITE.NS",
    "GSPL.NS",
    "HAPPSTMNDS.NS",
    "HATSUN.NS",
    "HERANBA.NS",
    "HINDCOPPER.NS",
    "HOMEFIRST.NS",
    "HSCL.NS",
    "IDBI.NS",
    "IDEA.NS",
    "IEX.NS",
    "INDIAMART.NS",
    "INDIANB.NS",
    "INDIGO.NS",
    "INTELLECT.NS",
    "IRB.NS",
    "JBCHEPHARM.NS",
    "JINDWORLD.NS",
    "JSL.NS",
    "JUBLINGREA.NS",
    "KAJARIACER.NS",
    "KALYANKJIL.NS",
    "KANSAINER.NS",
    "KEI.NS",
    "KPITTECH.NS",
    "LICHSGFIN.NS",
    "LODHA.NS",
    "LTTS.NS",
    "MAHABANK.NS",
    "MAHSCOOTER.NS",
    "MANAPPURAM.NS",
    "MASTEK.NS",
    "METROPOLIS.NS",
    "MFSL.NS",
    "MGL.NS",
    "MOTILALOFS.NS",
    "NAM-INDIA.NS",
    "NATIONALUM.NS",
    "NAVINFLUOR.NS",
    "NH.NS",
    "NLCINDIA.NS",
    "OBEROIRLTY.NS",
    "OIL.NS",
    "PATANJALI.NS",
    "POLICYBZR.NS",
    "POLYMED.NS",
    "PRESTIGE.NS",
    "RAINBOW.NS",
    "RAMCOCEM.NS",
    "RATNAMANI.NS",
    "RAYMOND.NS",
    "RBLBANK.NS",
    "SAIL.NS",
    "SCHAEFFLER.NS",
    "SCHNEIDER.NS",
    "SCI.NS",
    "SJVN.NS",
    "SKFINDIA.NS",
    "SOBHA.NS",
    "SONACOMS.NS",
    "STARHEALTH.NS",
    "SUMICHEM.NS",
    "SUNTV.NS",
    "SUPREMEIND.NS",
    "SYNGENE.NS",
    "TANLA.NS",
    "TATAELXSI.NS",
    "TATAINVEST.NS",
    "TECHNOE.NS",
    "THERMAX.NS",
    "TIMKEN.NS",
    "TITAGARH.NS",
    "TRIDENT.NS",
    "TTML.NS",
    "UJJIVANSFB.NS",
    "UNOMINDA.NS",
    "VGUARD.NS",
    "VIPIND.NS",
    "VMART.NS",
    "WELCORP.NS",
    "WESTLIFE.NS",
    "ZEEL.NS",
    "360ONE.NS",
    "AADHARHFC.NS",
    "AFFLE.NS",
    "APLAPOLLO.NS",
    "ASAHIINDIA.NS",
    "AWL.NS",
    "BALRAMCHIN.NS",
    "BANKINDIA.NS",
    "BDL.NS",
    "BEML.NS",
    "BIKAJI.NS",
    "BSOFT.NS",
    "CAMS.NS",
    "CARBORUNIV.NS",
    "CDSL.NS",
    "CGPOWER.NS",
    "CLEAN.NS",
    "DCMSHRIRAM.NS",
    "ECLERX.NS",
    "EMAMILTD.NS",
    "FINCABLES.NS",
    "FINPIPE.NS",
    "FSL.NS",
    "GILLETTE.NS",
    "GMDCLTD.NS",
    "GVT&D.NS",
    "HONAUT.NS",
    "IFCI.NS",
    "INDIACEM.NS",
    "IRCON.NS",
    "J&KBANK.NS",
    "JKTYRE.NS",
    "JWL.NS",
    "KPRMILL.NS",
    "LATENTVIEW.NS",
    "LEMONTREE.NS",
    "LLOYDSME.NS",
    "LODHA.NS",
    "MAPMYINDIA.NS",
    "MCX.NS",
    "MEDANTA.NS",
    "MSUMI.NS",
    "NETWORK18.NS",
    "NHPC.NS",
    "NSLNISP.NS",
    "OLECTRA.NS",
    "PCBL.NS",
    "PGEL.NS",
    "PGHH.NS",
    "POONAWALLA.NS",
    "PRAJIND.NS",
    "PTC.NS",
    "RITES.NS",
    "ROSSARI.NS",
    "RVNL.NS",
    "SAREGAMA.NS",
    "SAPPHIRE.NS",
    "SHYAMMETL.NS",
    "SUNDRMFAST.NS",
    "SUPRAJIT.NS",
    "SUZLON.NS",
    "SWANCORP.NS",
    "TARIL.NS",
    "TEJASNET.NS",
    "TRITURBINE.NS",
    "UTIAMC.NS",
    "VARROC.NS",
    "VIJAYA.NS",
    "ZENSARTECH.NS",
]

# Small cap: more speculative; keep names that often still print reasonable volume on NSE.
_SMALL_CAP_LIQUID: list[str] = [
    "ABSLAMC.NS",
    "ACE.NS",
    "AEGISLOG.NS",
    "AGI.NS",
    "AKZOINDIA.NS",
    "ALOKINDS.NS",
    "ANANTRAJ.NS",
    "APTUS.NS",
    "ASAHIINDIA.NS",
    "ASHIANA.NS",
    "ASTEC.NS",
    "BAJAJELEC.NS",
    "BALAMINES.NS",
    "BECTORFOOD.NS",
    "BIRLACORPN.NS",
    "BLUESTARCO.NS",
    "BORORENEW.NS",
    "CARERATING.NS",
    "CEATLTD.NS",
    "CENTURYPLY.NS",
    "CERA.NS",
    "CHEMPLASTS.NS",
    "CHOICEIN.NS",
    "CUB.NS",
    "DATAPATTNS.NS",
    "DBL.NS",
    "DHANI.NS",
    "EIDPARRY.NS",
    "ELGIEQUIP.NS",
    "EMBDL.NS",
    "EMIL.NS",
    "EPL.NS",
    "ERIS.NS",
    "FACT.NS",
    "FDC.NS",
    "FINOPB.NS",
    "FLUOROCHEM.NS",
    "GATEWAY.NS",
    "GENESYS.NS",
    "GESHIP.NS",
    "GMDCLTD.NS",
    "GPPL.NS",
    "GRINDWELL.NS",
    "GRSE.NS",
    "GSFC.NS",
    "GTPL.NS",
    "HAPPSTMNDS.NS",
    "HCG.NS",
    "HEG.NS",
    "HFCL.NS",
    "HIKAL.NS",
    "HLEGLAS.NS",
    "HSCL.NS",
    "IFBIND.NS",
    "IIFL.NS",
    "INDIASHLTR.NS",
    "INDIGOPNTS.NS",
    "INOXINDIA.NS",
    "ITI.NS",
    "JAMNAAUTO.NS",
    "JISLJALEQS.NS",
    "JUSTDIAL.NS",
    "KARURVYSYA.NS",
    "KITEX.NS",
    "KNRCON.NS",
    "KPIL.NS",
    "LATTEYS.NS",
    "LGBBROSLTD.NS",
    "LMW.NS",
    "MAHLIFE.NS",
    "MAHSEAMLES.NS",
    "MARKSANS.NS",
    "MASTEK.NS",
    "MAZDOCK.NS",
    "MIDHANI.NS",
    "MMTC.NS",
    "MOIL.NS",
    "MOTOGENFIN.NS",
    "NATCOPHARM.NS",
    "NAVA.NS",
    "NCC.NS",
    "NEULANDLAB.NS",
    "NEWGEN.NS",
    "NIVABUPA.NS",
    "NUVOCO.NS",
    "ORIENTCEM.NS",
    "PARADEEP.NS",
    "PARAS.NS",
    "PDSL.NS",
    "PNCINFRA.NS",
    "PRINCEPIPE.NS",
    "QUESS.NS",
    "RAILTEL.NS",
    "RALLIS.NS",
    "RATNAVEER.NS",
    "REDINGTON.NS",
    "RELINFRA.NS",
    "ROUTE.NS",
    "RTNINDIA.NS",
    "SAGILITY.NS",
    "SANOFI.NS",
    "SANSERA.NS",
    "SAPPHIRE.NS",
    "SARDAEN.NS",
    "SATIN.NS",
    "SEQUENT.NS",
    "SHARDACROP.NS",
    "SHOPERSTOP.NS",
    "SHRIRAMFIN.NS",
    "SIGNATURE.NS",
    "SIS.NS",
    "SOBHA.NS",
    "SOLARA.NS",
    "SPARC.NS",
    "STAR.NS",
    "SUNTECK.NS",
    "SUPRIYA.NS",
    "SWSOLAR.NS",
    "TANLA.NS",
    "TATAINVEST.NS",
    "TBOTEK.NS",
    "TEGA.NS",
    "THANGAMAYL.NS",
    "TIMETECHNO.NS",
    "TIPSMUSIC.NS",
    "TNPL.NS",
    "TVSSCS.NS",
    "UBL.NS",
    "USHAMART.NS",
    "VESUVIUS.NS",
    "VIJAYA.NS",
    "VIPIND.NS",
    "WABAG.NS",
    "WELSPUNLIV.NS",
    "WOCKPHARMA.NS",
    "YESBANK.NS",
    "ZENTEC.NS",
]


def _dedupe_preserve_order(tickers: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for t in tickers:
        u = t.strip().upper()
        if u and u not in seen:
            out.append(u)
            seen.add(u)
    return out


def get_large_cap_universe() -> list[str]:
    return _dedupe_preserve_order(list(NIFTY50_TICKERS) + _LARGE_CAP_EXTRA)


def get_mid_cap_universe() -> list[str]:
    return _dedupe_preserve_order(_MID_CAP)


def get_small_cap_universe() -> list[str]:
    return _dedupe_preserve_order(_SMALL_CAP_LIQUID)


def get_multi_layer_full_universe(*, max_names: int | None = None) -> list[str]:
    """
    Combined diversified universe (large + mid + small), de-duplicated.
    """
    u = _dedupe_preserve_order(get_large_cap_universe() + get_mid_cap_universe() + get_small_cap_universe())
    if max_names is not None and max_names > 0:
        return u[:max_names]
    return u


def parse_universe_override(text: str) -> list[str]:
    """Optional paste-in list to replace/augment defaults (comma / newline separated)."""
    return parse_tickers_text(text)
